# Generated by Django 5.1.3 on 2024-11-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='num_paginas',
            field=models.IntegerField(default=100),
        ),
    ]
